apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "singctl-license.fullname" . }}
  labels:
    {{- include "singctl-license.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate # single RWO PVC — never run two writers at once
  selector:
    matchLabels:
      {{- include "singctl-license.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "singctl-license.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        fsGroup: 65532
      containers:
        - name: server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["serve"]
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: LICENSE_ADDR
              value: ":8080"
            - name: LICENSE_DB
              value: "/data/licenses.json"
            - name: LICENSE_DEFAULT_TTL_DAYS
              value: "{{ .Values.defaultTTLDays }}"
            - name: LICENSE_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "singctl-license.secretName" . }}
                  key: privateKey
            - name: LICENSE_ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "singctl-license.secretName" . }}
                  key: adminToken
            - name: LICENSE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "singctl-license.secretName" . }}
                  key: webhookSecret
                  optional: true
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "singctl-license.fullname" . }}
        {{- else }}
          emptyDir: {}
        {{- end }}
