// Auto-generated by singctl (internal/sysproxy) — DO NOT EDIT BY HAND.
// Exclude-mode: proxy everything EXCEPT the [direct] rules below (plus the
// built-in bare-hostname rule, if enabled). [proxy] rules are checked FIRST
// and always win, even over a [direct] match.
function FindProxyForURL(url, host) {
    host = ("" + host).toLowerCase();
    var PROXY = "PROXY 127.0.0.1:2080";
    var DIRECT = "DIRECT";

    // 1) Bare/simple hostnames (no dots) — e.g. intranet shortcuts.
    if (isPlainHostName(host)) return DIRECT;

    // 2) Literal private IPs (guarded so we never trigger a DNS lookup).
    if (/^\d+(\.\d+){3}$/.test(host)) {
        if (isInNet(host, "10.0.0.0",    "255.0.0.0"))   return DIRECT;
        if (isInNet(host, "172.16.0.0",  "255.240.0.0")) return DIRECT;
        if (isInNet(host, "192.168.0.0", "255.255.0.0")) return DIRECT;
        if (isInNet(host, "100.64.0.0",  "255.192.0.0")) return DIRECT; // CGNAT
        if (isInNet(host, "169.254.0.0", "255.255.0.0")) return DIRECT; // link-local
        if (isInNet(host, "127.0.0.0",   "255.0.0.0"))   return DIRECT;
    }

    // 3) Wildcard [direct] rules (shell-glob patterns).
    if (shExpMatch(host, "*.ru") || host === "ru") return DIRECT;
    if (shExpMatch(host, "*.xn--p1ai")) return DIRECT;
    if (shExpMatch(host, "*.local")) return DIRECT;

    // 4) Domain [direct] rules — match host + subdomains.
    var D = {
        "2gis.com": 1,
        "3ebra.net": 1,
        "yandex.net": 1,
        "": 0
    };
    if (D[host]) return DIRECT;
    var i = host.indexOf(".");
    while (i >= 0) {
        if (D[host.substring(i + 1)]) return DIRECT;
        i = host.indexOf(".", i + 1);
    }

    return PROXY;
}
