// Auto-generated by singctl (internal/sysproxy) — DO NOT EDIT BY HAND.
// Include-mode: only the listed domains (and subdomains) use the proxy.
function FindProxyForURL(url, host) {
    host = ("" + host).toLowerCase();
    var PROXY = "PROXY 127.0.0.1:2080";
    var D = {
        "google.com": 1,
        "openai.com": 1,
        "anthropic.com": 1,
        "": 0
    };
    if (D[host]) return PROXY;
    var i = host.indexOf(".");
    while (i >= 0) {
        if (D[host.substring(i + 1)]) return PROXY;
        i = host.indexOf(".", i + 1);
    }
    return "DIRECT";
}
