package sysproxy

import (
	"fmt"
	"net"
	"path"
	"strings"
)

// GeneratePAC renders the Proxy Auto-Config script for cfg.Mode, which must
// be ModeInclude or ModeExclude (ModeOff has no PAC — the toggle is a manual
// networksetup disable instead). Deterministic in the input lists' order —
// see classifyRules.
func GeneratePAC(cfg Config) (string, error) {
	switch cfg.Mode {
	case ModeInclude:
		return GenerateIncludePAC(cfg.Proxy, cfg.ProxyDirective()), nil
	case ModeExclude:
		return GenerateExcludePAC(cfg.Proxy, cfg.Direct, cfg.ProxyDirective(), cfg.BypassPlainHostnames), nil
	default:
		return "", fmt.Errorf("sysproxy: mode %q has no PAC", cfg.Mode)
	}
}

// GenerateIncludePAC renders the include-mode PAC: only proxyRules (and
// their subdomains) go through proxyDirective; everything else is DIRECT.
// proxyRules may mix bare domains, glob patterns, and CIDRs — see
// classifyRules.
func GenerateIncludePAC(proxyRules []string, proxyDirective string) string {
	domains, globs, cidrs, nets := classifyRules(proxyRules)

	var b strings.Builder
	b.WriteString("// Auto-generated by singctl (internal/sysproxy) — DO NOT EDIT BY HAND.\n")
	b.WriteString("// Include-mode: only the listed domains (and subdomains) use the proxy.\n")
	b.WriteString("function FindProxyForURL(url, host) {\n")
	b.WriteString("    host = (\"\" + host).toLowerCase();\n")
	fmt.Fprintf(&b, "    var PROXY = %q;\n", proxyDirective)

	if len(nets) > 0 {
		b.WriteString("    if (/^\\d+(\\.\\d+){3}$/.test(host)) {\n")
		writeCIDRChecks(&b, cidrs, nets, "PROXY")
		b.WriteString("    }\n")
	}
	writeGlobChecks(&b, globs, "PROXY")

	if len(domains) > 0 {
		writeDomainBlock(&b, "D", domains, "PROXY")
	}
	b.WriteString("    return \"DIRECT\";\n")
	b.WriteString("}\n")
	return b.String()
}

// GenerateExcludePAC renders the exclude-mode PAC: everything goes through
// proxyDirective EXCEPT what directRules matches (plus bare/simple hostnames
// when bypassPlainHostnames is set) — UNLESS a host also matches
// proxyRules, which is checked FIRST and always wins (see ParseINI's doc
// comment on [proxy] vs [direct] precedence). Both rule lists may mix bare
// domains, glob patterns, and CIDRs — see classifyRules.
func GenerateExcludePAC(proxyRules, directRules []string, proxyDirective string, bypassPlainHostnames bool) string {
	pDomains, pGlobs, pCidrs, pNets := classifyRules(proxyRules)
	dDomains, dGlobs, dCidrs, dNets := classifyRules(directRules)

	var b strings.Builder
	b.WriteString("// Auto-generated by singctl (internal/sysproxy) — DO NOT EDIT BY HAND.\n")
	b.WriteString("// Exclude-mode: proxy everything EXCEPT the [direct] rules below (plus the\n")
	b.WriteString("// built-in bare-hostname rule, if enabled). [proxy] rules are checked FIRST\n")
	b.WriteString("// and always win, even over a [direct] match.\n")
	b.WriteString("function FindProxyForURL(url, host) {\n")
	b.WriteString("    host = (\"\" + host).toLowerCase();\n")
	fmt.Fprintf(&b, "    var PROXY = %q;\n", proxyDirective)
	b.WriteString("    var DIRECT = \"DIRECT\";\n")

	if len(pDomains) > 0 || len(pGlobs) > 0 || len(pNets) > 0 {
		b.WriteString("\n")
		b.WriteString("    // 0) Explicit [proxy] override — wins over every DIRECT rule below.\n")
		if len(pNets) > 0 {
			b.WriteString("    if (/^\\d+(\\.\\d+){3}$/.test(host)) {\n")
			writeCIDRChecks(&b, pCidrs, pNets, "PROXY")
			b.WriteString("    }\n")
		}
		writeGlobChecks(&b, pGlobs, "PROXY")
		if len(pDomains) > 0 {
			writeDomainBlock(&b, "P", pDomains, "PROXY")
		}
	}

	if bypassPlainHostnames {
		b.WriteString("\n")
		b.WriteString("    // 1) Bare/simple hostnames (no dots) — e.g. intranet shortcuts.\n")
		b.WriteString("    if (isPlainHostName(host)) return DIRECT;\n")
	}

	if len(dNets) > 0 {
		b.WriteString("\n")
		b.WriteString("    // 2) Literal private IPs (guarded so we never trigger a DNS lookup).\n")
		b.WriteString("    if (/^\\d+(\\.\\d+){3}$/.test(host)) {\n")
		writeCIDRChecks(&b, dCidrs, dNets, "DIRECT")
		b.WriteString("    }\n")
	}

	if len(dGlobs) > 0 {
		b.WriteString("\n")
		b.WriteString("    // 3) Wildcard [direct] rules (shell-glob patterns).\n")
		writeGlobChecks(&b, dGlobs, "DIRECT")
	}

	if len(dDomains) > 0 {
		b.WriteString("\n")
		b.WriteString("    // 4) Domain [direct] rules — match host + subdomains.\n")
		writeDomainBlock(&b, "D", dDomains, "DIRECT")
	}

	b.WriteString("\n")
	b.WriteString("    return PROXY;\n")
	b.WriteString("}\n")
	return b.String()
}

// classifyRules splits a Proxy/Direct rule list into its three shapes, each
// normalized (lowercased/trimmed) and in original relative order:
//
//   - domains: a bare entry (no "*", no "/") — matched against the host
//     itself and every subdomain (see writeDomainBlock / matchesDomainSuffix).
//   - globs: any entry containing "*" (e.g. "*.githubusercontent.com", the
//     organization-specific wildcards) — matched via shell-glob semantics (see globMatch).
//   - cidrs/nets: an entry containing "/" that parses as an IPv4 CIDR —
//     matched only against a literal IPv4 host, never a DNS lookup. A
//     malformed or non-IPv4 CIDR is dropped here (Config.Validate/ParseINI
//     are what reject those loudly at config-load time; by the time
//     GeneratePAC runs, cfg is assumed already validated).
//
// cidrs and nets are parallel (same length, same order) — cidrs carries the
// original normalized text so writeCIDRChecks can look up per-CIDR
// annotations (see cidrAnnotations) by exact string.
func classifyRules(rules []string) (domains, globs, cidrs []string, nets []*net.IPNet) {
	seenDomain := make(map[string]bool)
	for _, raw := range rules {
		e := strings.ToLower(strings.TrimSpace(raw))
		if e == "" {
			continue
		}
		switch {
		case strings.Contains(e, "/"):
			if _, n, err := net.ParseCIDR(e); err == nil && n.IP.To4() != nil {
				cidrs = append(cidrs, e)
				nets = append(nets, n)
			}
		case strings.Contains(e, "*"):
			globs = append(globs, e)
		default:
			if !seenDomain[e] {
				seenDomain[e] = true
				domains = append(domains, e)
			}
		}
	}
	return domains, globs, cidrs, nets
}

// writeDomainBlock renders a "var <varName> = {...}; if (<varName>[host])
// return <ret>; <suffix walk>" block — the same O(labels-per-host) hash-object
// matching gen-pac.sh/gen-exclude-pac.sh used, ported verbatim: host itself
// or any of its parent domains being a key returns ret.
func writeDomainBlock(b *strings.Builder, varName string, domains []string, ret string) {
	fmt.Fprintf(b, "    var %s = {\n", varName)
	for _, d := range domains {
		fmt.Fprintf(b, "        %q: 1,\n", d)
	}
	b.WriteString("        \"\": 0\n")
	b.WriteString("    };\n")
	fmt.Fprintf(b, "    if (%s[host]) return %s;\n", varName, ret)
	b.WriteString("    var i = host.indexOf(\".\");\n")
	b.WriteString("    while (i >= 0) {\n")
	fmt.Fprintf(b, "        if (%s[host.substring(i + 1)]) return %s;\n", varName, ret)
	b.WriteString("        i = host.indexOf(\".\", i + 1);\n")
	b.WriteString("    }\n")
}

// writeGlobChecks renders one `if (shExpMatch(host, "<glob>")) return <ret>;`
// line per glob.
//
// SPECIAL CASE: "*.ru" additionally checks `|| host === "ru"`, mirroring the
// original hardcoded PAC's shortcut for the bare "ru" ccTLD itself (a
// legitimate, if unusual, host). This is intentionally NOT generalized to
// every "*.X" pattern — it was a one-off in the original gen-exclude-pac.sh
// and is kept only for that exact literal, for both behavioural and
// (default-config) byte-for-byte parity.
func writeGlobChecks(b *strings.Builder, globs []string, ret string) {
	for _, g := range globs {
		extra := ""
		if g == "*.ru" {
			extra = ` || host === "ru"`
		}
		fmt.Fprintf(b, "    if (shExpMatch(host, %q)%s) return %s;\n", g, extra, ret)
	}
}

// cidrAnnotations are informational trailing comments for well-known CIDRs —
// purely cosmetic, applied whenever these exact literals appear in a rule
// list (default or user-supplied alike). Any other CIDR gets no comment.
var cidrAnnotations = map[string]string{
	"100.64.0.0/10":  "CGNAT",
	"169.254.0.0/16": "link-local",
}

// writeCIDRChecks renders one column-aligned `if (isInNet(host, "<net>",
// "<mask>")) return <ret>;` line per net, inside the caller-written
// `if (/^\d+(\.\d+){3}$/.test(host)) { ... }` IPv4-literal guard. Column
// widths are computed from the actual entries (not hardcoded), so this
// reproduces the original hand-aligned formatting for DefaultDirectRules'
// six ranges and still degrades gracefully (just less fussy alignment) for
// an arbitrary custom CIDR list.
func writeCIDRChecks(b *strings.Builder, cidrs []string, nets []*net.IPNet, ret string) {
	type row struct{ netField, maskField, comment string }
	rows := make([]row, len(nets))
	maxNet, maxMask := 0, 0
	for i, n := range nets {
		rows[i].netField = fmt.Sprintf("%q,", n.IP.String())
		rows[i].maskField = fmt.Sprintf("%q))", dottedMask(n.Mask))
		if c, ok := cidrAnnotations[cidrs[i]]; ok {
			rows[i].comment = " // " + c
		}
		if l := len(rows[i].netField); l > maxNet {
			maxNet = l
		}
		if l := len(rows[i].maskField); l > maxMask {
			maxMask = l
		}
	}
	netW, maskW := maxNet+1, maxMask+1
	for _, r := range rows {
		fmt.Fprintf(b, "        if (isInNet(host, %-*s%-*sreturn %s;%s\n", netW, r.netField, maskW, r.maskField, ret, r.comment)
	}
}

// dottedMask renders an IPv4 subnet mask in dotted-decimal form, as
// isInNet's second argument expects.
func dottedMask(m net.IPMask) string {
	if len(m) != net.IPv4len {
		if m4 := net.IP(m).To4(); m4 != nil {
			m = net.IPMask(m4)
		}
	}
	return net.IP(m).String()
}

// MatchesExcludeDirect reports whether host resolves to DIRECT under
// GenerateExcludePAC(cfg.Proxy, cfg.Direct, ..., cfg.BypassPlainHostnames)'s
// rules. It mirrors that PAC's FindProxyForURL logic exactly, rule for rule
// (including the [proxy]-wins-first precedence), so tests can pin the
// domain-rule semantics without a JavaScript engine.
func MatchesExcludeDirect(cfg Config, host string) bool {
	host = strings.ToLower(strings.TrimSpace(host))

	// 0) [proxy] override wins over everything below.
	if matchesRuleSet(cfg.Proxy, host) {
		return false
	}

	// 1) Bare/simple hostnames (no dots).
	if cfg.BypassPlainHostnames && !strings.Contains(host, ".") {
		return true
	}

	// 2/3/4) [direct] rules (CIDR literal / glob / domain+subdomain).
	return matchesRuleSet(cfg.Direct, host)
}

// MatchesIncludeProxy reports whether host is proxied under
// GenerateIncludePAC(cfg.Proxy, ...)'s rules: host matches a Proxy entry
// (domain+subdomain, glob, or literal-IP CIDR).
func MatchesIncludeProxy(cfg Config, host string) bool {
	return matchesRuleSet(cfg.Proxy, strings.ToLower(strings.TrimSpace(host)))
}

// matchesRuleSet reports whether host (already lowercased/trimmed) matches
// any entry in rules, across all three shapes — the Go-side mirror of what
// writeDomainBlock/writeGlobChecks/writeCIDRChecks render into the PAC.
func matchesRuleSet(rules []string, host string) bool {
	domains, globs, _, nets := classifyRules(rules)
	if matchesDomainSuffix(domains, host) {
		return true
	}
	for _, g := range globs {
		if globMatch(g, host) {
			return true
		}
		if g == "*.ru" && host == "ru" { // see writeGlobChecks' special case
			return true
		}
	}
	if ip := net.ParseIP(host); ip != nil {
		for _, n := range nets {
			if n.Contains(ip) {
				return true
			}
		}
	}
	return false
}

// matchesDomainSuffix walks host's dotted suffixes exactly like the PAC's
// `while (i = host.indexOf("."...))` loop: host itself, then each
// ever-shorter parent domain, against the normalized domain set. domains is
// assumed already normalized (see classifyRules) — callers passing a raw
// Config field should go through matchesRuleSet instead.
func matchesDomainSuffix(domains []string, host string) bool {
	set := make(map[string]bool, len(domains))
	for _, d := range domains {
		set[d] = true
	}
	if set[host] {
		return true
	}
	i := strings.IndexByte(host, '.')
	for i >= 0 {
		if set[host[i+1:]] {
			return true
		}
		j := strings.IndexByte(host[i+1:], '.')
		if j < 0 {
			break
		}
		i += 1 + j
	}
	return false
}

// globMatch implements the subset of shell glob (only "*") that
// gen-exclude-pac.sh's shExpMatch calls use. path.Match applies the same
// algorithm shExpMatch does and, since hosts never contain "/", behaves
// identically to a full shell glob here.
func globMatch(pattern, s string) bool {
	ok, err := path.Match(pattern, s)
	return err == nil && ok
}
