// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bridge} from '../models';

export function ActivateLicense(arg1:string,arg2:string):Promise<void>;

export function AddKey(arg1:string):Promise<void>;

export function ApplySettings(arg1:bridge.Settings):Promise<void>;

export function DeleteKey(arg1:number):Promise<void>;

export function GetKeys():Promise<Array<bridge.Key>>;

export function GetLicense():Promise<bridge.LicenseInfo>;

export function GetSettings():Promise<bridge.Settings>;

export function GetStatus():Promise<bridge.Status>;

export function KillPID(arg1:number):Promise<void>;

export function LaunchApp(arg1:Array<string>):Promise<number>;

export function ListApplications():Promise<Array<bridge.Application>>;

export function ListProcesses():Promise<Array<bridge.ProcInfo>>;

export function ListRouted():Promise<Array<number>>;

export function ListRoutedApps():Promise<Array<string>>;

export function RemoveLicense():Promise<void>;

export function RenameKey(arg1:number,arg2:string):Promise<void>;

export function RestartPID(arg1:number):Promise<number>;

export function RouteApp(arg1:string):Promise<void>;

export function RoutePID(arg1:number):Promise<void>;

export function SetMode(arg1:string):Promise<void>;

export function StopDaemon():Promise<void>;

export function UnrouteApp(arg1:string):Promise<void>;

export function UnroutePID(arg1:number):Promise<void>;
