// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateLicense(arg1) {
  return window['go']['bridge']['App']['ActivateLicense'](arg1);
}

export function AddKey(arg1) {
  return window['go']['bridge']['App']['AddKey'](arg1);
}

export function ApplySettings(arg1) {
  return window['go']['bridge']['App']['ApplySettings'](arg1);
}

export function DeleteKey(arg1) {
  return window['go']['bridge']['App']['DeleteKey'](arg1);
}

export function GetKeys() {
  return window['go']['bridge']['App']['GetKeys']();
}

export function GetLicense() {
  return window['go']['bridge']['App']['GetLicense']();
}

export function GetSettings() {
  return window['go']['bridge']['App']['GetSettings']();
}

export function GetStatus() {
  return window['go']['bridge']['App']['GetStatus']();
}

export function KillPID(arg1) {
  return window['go']['bridge']['App']['KillPID'](arg1);
}

export function LaunchApp(arg1) {
  return window['go']['bridge']['App']['LaunchApp'](arg1);
}

export function ListProcesses() {
  return window['go']['bridge']['App']['ListProcesses']();
}

export function ListRouted() {
  return window['go']['bridge']['App']['ListRouted']();
}

export function RemoveLicense() {
  return window['go']['bridge']['App']['RemoveLicense']();
}

export function RenameKey(arg1, arg2) {
  return window['go']['bridge']['App']['RenameKey'](arg1, arg2);
}

export function RestartPID(arg1) {
  return window['go']['bridge']['App']['RestartPID'](arg1);
}

export function RoutePID(arg1) {
  return window['go']['bridge']['App']['RoutePID'](arg1);
}

export function SetMode(arg1) {
  return window['go']['bridge']['App']['SetMode'](arg1);
}

export function StopDaemon() {
  return window['go']['bridge']['App']['StopDaemon']();
}

export function UnroutePID(arg1) {
  return window['go']['bridge']['App']['UnroutePID'](arg1);
}
