#!/usr/bin/env bash
# Generate a macOS PAC for EXCLUDE mode (proxy-on): send EVERYTHING through the
# proxy EXCEPT traffic that should stay direct — corporate resources, Russian
# domains, and bare/simple hostnames.
#
# Usage: gen-exclude-pac.sh <ru-domains-file> <proxy-directive>
#   e.g. gen-exclude-pac.sh ru-extra.txt "PROXY 127.0.0.1:2080"
#
# DIRECT (not proxied) when the host is:
#   - a simple/bare hostname with no dots   (isPlainHostName — "exclude simple hostnames")
#   - a literal IP inside the corporate/private ranges (RFC1918 + CGNAT + link-local)
#   - under any ExampleOrganization domain                   (*.ExampleOrganization.* — corporate, verified live)
#   - a .ru or .рф(xn--p1ai) domain         (wildcards)
#   - listed in <ru-domains-file>           (Russian services on non-.ru TLDs)
# Everything else -> the proxy directive.
set -euo pipefail

RU_FILE="${1:?usage: gen-exclude-pac.sh <ru-domains-file> <proxy-directive>}"
PROXY_DIRECTIVE="${2:?e.g. \"PROXY 127.0.0.1:2080\"}"

entries=""
if [ -f "$RU_FILE" ]; then
  entries="$(awk '
    { sub(/#.*/, ""); gsub(/[ \t\r]/, ""); if ($0 != "") printf "    \"%s\": 1,\n", tolower($0) }
  ' "$RU_FILE")"
fi
count="$(printf '%s\n' "$entries" | grep -c ':' || true)"
echo "gen-exclude-pac: ${count} RU domains + wildcards -> PAC (proxy: ${PROXY_DIRECTIVE})" >&2

cat <<EOF
// Auto-generated by packaging/macos/gen-exclude-pac.sh — DO NOT EDIT BY HAND.
// Exclude-mode: proxy everything EXCEPT corporate + Russian + simple hostnames.
function FindProxyForURL(url, host) {
    host = ("" + host).toLowerCase();
    var PROXY = "${PROXY_DIRECTIVE}";
    var DIRECT = "DIRECT";

    // 1) Bare/simple hostnames (no dots) — e.g. intranet shortcuts.
    if (isPlainHostName(host)) return DIRECT;

    // 2) Literal private/corporate IPs (guarded so we never trigger a DNS lookup).
    if (/^\d+(\.\d+){3}\$/.test(host)) {
        if (isInNet(host, "10.0.0.0",    "255.0.0.0"))   return DIRECT;
        if (isInNet(host, "172.16.0.0",  "255.240.0.0")) return DIRECT;
        if (isInNet(host, "192.168.0.0", "255.255.0.0")) return DIRECT;
        if (isInNet(host, "100.64.0.0",  "255.192.0.0")) return DIRECT; // CGNAT (corp)
        if (isInNet(host, "169.254.0.0", "255.255.0.0")) return DIRECT; // link-local
        if (isInNet(host, "127.0.0.0",   "255.0.0.0"))   return DIRECT;
    }

    // 3) Corporate ExampleOrganization on any TLD, and Russian TLDs (.ru / .рф=xn--p1ai).
    if (shExpMatch(host, "*.ExampleOrganization.*")) return DIRECT;
    if (shExpMatch(host, "*.ru") || host === "ru") return DIRECT;
    if (shExpMatch(host, "*.xn--p1ai")) return DIRECT;
    if (shExpMatch(host, "*.local")) return DIRECT;

    // 4) Russian services on non-.ru TLDs (fetched list) — match host + subdomains.
    var D = {
${entries}
        "": 0
    };
    if (D[host]) return DIRECT;
    var i = host.indexOf(".");
    while (i >= 0) {
        if (D[host.substring(i + 1)]) return DIRECT;
        i = host.indexOf(".", i + 1);
    }

    return PROXY;
}
EOF
