#!/usr/bin/env bash
# Generate a macOS Proxy Auto-Config (PAC) file from a plain domain allowlist.
#
# Usage: gen-pac.sh <domains-file> <proxy-directive>
#   e.g. gen-pac.sh proxy-domains.txt "PROXY 127.0.0.1:2080"
#
# The PAC is written to stdout. Everything NOT in the list resolves to DIRECT,
# so this is include-mode: only the listed domains (and their subdomains) are
# sent through the proxy. Matching walks the host's dotted suffixes against a
# hash object, so a list of thousands stays O(labels-per-host) per request.
set -euo pipefail

DOMAINS_FILE="${1:?usage: gen-pac.sh <domains-file> <proxy-directive>}"
PROXY_DIRECTIVE="${2:?e.g. \"PROXY 127.0.0.1:2080\"}"

# Strip inline/full-line comments and whitespace; emit one JS object entry per
# domain. Trailing commas are legal-enough for PAC engines, but we cap the
# object with a sentinel so the JS stays strictly valid.
entries="$(awk '
  { sub(/#.*/, ""); gsub(/[ \t\r]/, ""); if ($0 != "") printf "    \"%s\": 1,\n", tolower($0) }
' "$DOMAINS_FILE")"

count="$(printf '%s\n' "$entries" | grep -c ':' || true)"
echo "gen-pac: ${count} domains -> PAC (proxy: ${PROXY_DIRECTIVE})" >&2

cat <<EOF
// Auto-generated by packaging/macos/gen-pac.sh — DO NOT EDIT BY HAND.
// Source: packaging/macos/proxy-domains.txt
// Include-mode: only the listed domains (and subdomains) use the proxy.
function FindProxyForURL(url, host) {
    host = ("" + host).toLowerCase();
    var PROXY = "${PROXY_DIRECTIVE}";
    var D = {
${entries}
        "": 0
    };
    if (D[host]) return PROXY;
    var i = host.indexOf(".");
    while (i >= 0) {
        if (D[host.substring(i + 1)]) return PROXY;
        i = host.indexOf(".", i + 1);
    }
    return "DIRECT";
}
EOF
